version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - echo Install step...
  pre_build:
    commands:
      - echo Logging in to AWS ECR...
      - aws --version
      - $(aws ecr get-login --no-include-email --region eu-central-1)
      - REPOSITORY_URI=206079280332.dkr.ecr.eu-central-1.amazonaws.com/translation
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build step...
      - echo Build Docker image on $(date)
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Post Build step...
      - echo Build Docker image completed on $(date)
      - echo Push latest Docker images to ECR...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - printf '[{"name":"translation","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
    files: imagedefinitions.json
